---
# tasks file for ansible-drbd

- include: debian.yml
  tags:
    - drbd
  when: ansible_os_family == "Debian"

- include: redhat.yml
  tags:
    - drbd
  when: ansible_os_family == "RedHat"

- include: disks.yml
  tags:
    - drbd
    - drbd-config
    - drbd-disks

- include: heartbeat.yml
  tags:
    - drbd
    - drbd-heartbeat
  when: drbd_use_heartbeat

- include: config.yml
  tags:
    - drbd
    - drbd-config

- include: services.yml
  tags:
    - drbd
    - drbd-services
