---
# tasks file for ansible-drbd

- name: Set quorum fact
  set_fact:
    drbd_quorum: "{{ drbd_quorum }}"

- include_tasks: debian.yml
  tags:
    - drbd
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  tags:
    - drbd
  when: ansible_os_family == "RedHat"

- include_tasks: disks.yml
  tags:
    - drbd
    - drbd-config
    - drbd-disks

- include_tasks: heartbeat.yml
  tags:
    - drbd
    - drbd-heartbeat
  when: drbd_use_heartbeat and drbd_quorum is sameas false

- include_tasks: config.yml
  tags:
    - drbd
    - drbd-config

- include_tasks: services.yml
  tags:
    - drbd
    - drbd-services
